#!/bin/bash
#
#*************************
#Jason Laske
#Dr. Lakshamanan
#CSC209 Assignment10 friday13th
#Date Due: 5/7/2014
#Date Submitted: 5/7/2014
#*************************
#
#****************************************************************
# Enter the while loop to run multiple iterations of the program
#****************************************************************

 # continueFlag=1
 # while [[ $continueFlag -eq 1 ]]
 # do
 
 #echo ""
 #echo -n "Enter the command (usage: $0 integer1 ...): "; read add  

#****************************************************************
# Check for command line arguments, if none set year to this year
#****************************************************************
 
 echo ""
  if [[ $# -eq 0 ]]
   then
     year=`date +%Y`
   else 
     year=$1
  fi

#****************************************************************
# Set up some Variables
#****************************************************************

   num=0
   total=0
   i=1

#****************************************************************
# Control structure to handle the computation
#****************************************************************
 
  for i in `seq 1 12`
  do
    num=`cal $i $year | awk '{print $6}' | grep 13 | wc -l`  
    total=$(($num + $total))
    i=$(($i + 1))
  done

#****************************************************************
# Output the total
#****************************************************************

 echo "The number of Friday the 13th in year $year is: $total"

#****************************************************************
# Ask to continue running the program
#****************************************************************

 echo ""
 #echo -n "Would you like to continue? (y to continue)"; read continue

#DEBUG#  echo "$continue"

    #if [[ $continue != "y" ]]
    # then
    #    continueFlag=0
    #else
    #    continueFlag=1
    #fi
 echo ""
 #done

#****************************************************************
# Exit the program
#****************************************************************

 exit 0

#
