#!/bin/bash
#
#*************************
#Jason Laske
#Dr. Lakshamanan
#CSC209 Assignment10 delete
#Date Due: 5/7/2014
#Date Submitted: 5/7/2014
#*************************
#
#****************************************************************
# Describe the purpose of this program
#****************************************************************
#
# The program will remove the named file/directory from the current 
# working directory and place it in ~/.trash."
# Invoke as 
# ./delete filename
#
#****************************************************************
# Enter the while loop to run multiple iterations of the program
#****************************************************************

 #continueFlag=1
 #while [[ $continueFlag -eq 1 ]]
 #do
 
 #echo ""
 #echo -n "Enter the command (usage: $0 integer1 ...): "; read add  

#****************************************************************
# Check for command line arguments
#****************************************************************
 
 echo ""
 if [[ $# -ne 1 ]]
  then
     echo "usage: $0 filename"
     exit 1
 fi

#****************************************************************
# Check if the named entry exists in the cwd
#****************************************************************

 if [[ !(-e $1) ]]
  then
     echo "$0: $1 does not exist"
     exit 2
 fi

#****************************************************************
# Check if ~/.trash exists; crate one if necessary
#****************************************************************

 if [[ !(-d ~/.trash) ]]
   then  
      mkdir ~/.trash
 fi
 
#****************************************************************
# Check if ~/.trash contains an entry with the given name 
#****************************************************************

 if [[ -e ~/.trash/$1 ]]
   then 
      echo -n "$0: $1 exists in .trash. Overwrite? (y/n) "
      read resp
      if [[ $resp == "y" ]]
        then
  	   rm -rf ~/.trash/$1
        else
           echo "$0: $1 is not deleted"
	   exit 3
      fi
 fi

#****************************************************************
# Move the enty from the cwd to ~/.trash
#****************************************************************
 
 mv $1 ~/.trash

#****************************************************************
# Ask to continue running the program
#****************************************************************

 #echo ""
 #echo -n "Would you like to continue? (y to continue)"; read continue

 #DEBUG#  #echo "$continue"

    #if [[ $continue != "y" ]]
    #then
    #   continueFlag=0
    #else
    #    continueFlag=1
    #fi
 #echo ""
 #done

#****************************************************************
# Exit the program
#****************************************************************

 exit 0

#
