package userinterface;

import java.awt.Image;

import javax.swing.ImageIcon;

public class ImageHolder {
	public ImageHolder(String imageFolder){
		if (IMG_DONE){
			return;
		}
		IMG_DONE = true;
		NUM_MENU_IMGS = 5;
		BK_IMG_0 = new ImageIcon(imageFolder + "FullCenterPaneC.png").getImage();
		JPI_BK_IMG_0 = new ImageIcon(imageFolder + "InfoPanel.png").getImage();
		LG_BK_IMG_0 = new ImageIcon(imageFolder + "TitleBar1.png").getImage();
		LG_BK_IMG_1 = new ImageIcon(imageFolder + "TitleFinalD.png").getImage();
		ViewL.DEF_BK_IMG = ImageHolder.BK_IMG_0;
		ICS_LOGOUT = new ImageIcon(imageFolder + "LogOutD.png");
		ICS_LOGOUT_HOVER = new ImageIcon(imageFolder + "LogOutHoverD.png");
		ICS_CHANGE_PASSWORD = new ImageIcon(imageFolder + "ChangePasswordD.png");
		ICS_CHANGE_PASSWORD_HOVER = new ImageIcon(imageFolder + "ChangePasswordHoverD.png");
		IC_ADD_BOOK = new ImageIcon(imageFolder + "AddBookC.png");
		IC_ADD_BOOK_HOVER = new ImageIcon(imageFolder + "AddBookHoverC.png");
		IC_MODIFY_BOOK = new ImageIcon(imageFolder + "ModifyBookC.png");
		IC_MODIFY_BOOK_HOVER = new ImageIcon(imageFolder + "ModifyBookHoverC.png");
		IC_DELETE_BOOK = new ImageIcon(imageFolder + "DeleteBookC.png");
		IC_DELETE_BOOK_HOVER = new ImageIcon(imageFolder + "DeleteBookHoverC.png");
		IC_ADD_BORROWER = new ImageIcon(imageFolder + "AddStudentC.png");
		IC_ADD_BORROWER_HOVER = new ImageIcon(imageFolder + "AddStudentHoverC.png");
		IC_MODIFY_BORROWER = new ImageIcon(imageFolder + "ModifyStudentC.png");
		IC_MODIFY_BORROWER_HOVER = new ImageIcon(imageFolder + "ModifyStudentHoverC.png");
		IC_DELETE_BORROWER = new ImageIcon(imageFolder + "DeleteStudentC.png");
		IC_DELETE_BORROWER_HOVER = new ImageIcon(imageFolder + "DeleteStudentHoverC.png");
		IC_ADD_WORKER = new ImageIcon(imageFolder + "AddWorkerC.png");
		IC_ADD_WORKER_HOVER = new ImageIcon(imageFolder + "AddWorkerHoverC.png");
		IC_MODIFY_WORKER = new ImageIcon(imageFolder + "ModifyWorkerC.png");
		IC_MODIFY_WORKER_HOVER = new ImageIcon(imageFolder + "ModifyWorkerHoverC.png");
		IC_DELETE_WORKER = new ImageIcon(imageFolder + "DeleteWorkerC.png");
		IC_DELETE_WORKER_HOVER = new ImageIcon(imageFolder + "DeleteWorkerHoverC.png");
		IC_CHECK_IN_BOOK = new ImageIcon(imageFolder + "CheckInBookF.png");
		IC_CHECK_IN_BOOK_HOVER = new ImageIcon(imageFolder + "CheckInBookHoverF.png");
		IC_CHECK_OUT_BOOK = new ImageIcon(imageFolder + "CheckOutBookF.png");
		IC_CHECK_OUT_BOOK_HOVER = new ImageIcon(imageFolder + "CheckedOutBookHoverF.png");
      IC_PROCESS_LOST_BOOK = new ImageIcon(imageFolder + "ProcessLostBookF.png");
		IC_PROCESS_LOST_BOOK_HOVER = new ImageIcon(imageFolder + "ProcessLostBookHoverF.png");
		IC_AVAILABLE_BOOKS = new ImageIcon(imageFolder + "AvailableBooksF.png");
		IC_AVAILABLE_BOOKS_HOVER = new ImageIcon(imageFolder + "AvailableBooksHoverF.png");
		IC_CHECKED_OUT_BOOKS = new ImageIcon(imageFolder + "CheckedOutBooksF.png");
		IC_CHECKED_OUT_BOOKS_HOVER = new ImageIcon(imageFolder + "CheckedOutBooksHoverF.png");
		IC_SB_WITH_CO_BOOKS = new ImageIcon(imageFolder + "StudentRentalsF.png");
		IC_SB_WITH_CO_BOOKS_HOVER = new ImageIcon(imageFolder + "StudentRentalsHoverF.png");
		IC_DELINQUNECY_CHECK = new ImageIcon(imageFolder + "DelinquencyCheckF.png");
		IC_DELINQUNECY_CHECK_HOVER = new ImageIcon(imageFolder + "DelinquencyCheckHoverF.png");
		ICS = new ImageIcon[NUM_MENU_IMGS];
		ICS[0] = new ImageIcon(imageFolder + "RentalButton2.png");
		ICS[1] = new ImageIcon(imageFolder + "BooksButton2.png");
		ICS[2] = new ImageIcon(imageFolder + "StudentButton2.png");
		ICS[3] = new ImageIcon(imageFolder + "WorkerButton2.png");
		ICS[4] = new ImageIcon(imageFolder + "ReportsButtons2.png");
		ICSP = new ImageIcon[NUM_MENU_IMGS];
		ICSP[0] = new ImageIcon(imageFolder + "RentalDownD.png");
		ICSP[1] = new ImageIcon(imageFolder + "BookDownD.png");
		ICSP[2] = new ImageIcon(imageFolder + "StudentDownD.png");
		ICSP[3] = new ImageIcon(imageFolder + "WorkerDownD.png");
		ICSP[4] = new ImageIcon(imageFolder + "ReportsDownD.png");
		ICSH = new ImageIcon[NUM_MENU_IMGS];
		ICSH[0] = new ImageIcon(imageFolder + "RentalHoverE.png");
		ICSH[1] = new ImageIcon(imageFolder + "BookHoverE.png");
		ICSH[2] = new ImageIcon(imageFolder + "StudentHoverE.png");
		ICSH[3] = new ImageIcon(imageFolder + "WorkerHoverE.png");
		ICSH[4] = new ImageIcon(imageFolder + "ReportsHoverE.png");
		ICB_LOGIN = new ImageIcon(imageFolder + "LogInD.png");
		ICB_CANCEL = new ImageIcon(imageFolder + "CancelButtonC.png");
		ICB_BACK = new ImageIcon(imageFolder + "Back.png");
		ICB_DONE = new ImageIcon(imageFolder + "DoneButtonC.png");
		ICB_SEARCH = new ImageIcon(imageFolder + "SearchButtonC.png");
		ICB_SELECT = new ImageIcon(imageFolder + "Select.png");
		ICB_SUBMIT = new ImageIcon(imageFolder + "SubmitButtonC.png");
		ICB_PRINT = new ImageIcon(imageFolder + "PrintButtonC.png");
		ICB_PROCESSFEE = new ImageIcon(imageFolder + "ProcessFeeButtonC.png");
		ICB_EXIT = new ImageIcon(imageFolder + "ExitButtonC.png");
		ICB_VALIDATE = new ImageIcon(imageFolder + "ValidateA.png");
		ICB_EXPORT = new ImageIcon(imageFolder + "Export.png");
		ICB_LOGIN_HOVER = new ImageIcon(imageFolder + "LogInHoverD.png");
		ICB_CANCEL_HOVER = new ImageIcon(imageFolder + "CancelHoverC.png");
		ICB_BACK_HOVER = new ImageIcon(imageFolder + "BackHover.png");
		ICB_DONE_HOVER = new ImageIcon(imageFolder + "DoneHoverC.png");
		ICB_SEARCH_HOVER = new ImageIcon(imageFolder + "SearchHoverC.png");
		ICB_SELECT_HOVER = new ImageIcon(imageFolder + "SelectHover.png");
		ICB_SUBMIT_HOVER = new ImageIcon(imageFolder + "SubmitHoverC.png");
		ICB_PRINT_HOVER = new ImageIcon(imageFolder + "PrintHoverC.png");
      ICB_PROCESS_BARCODE = new ImageIcon(imageFolder + "ProcessBarcode.png");
      ICB_PROCESS_BARCODE_HOVER = new ImageIcon(imageFolder + "ProcessBarcodeHover.png");
      ICB_PROCESS_NEW_BARCODE = new ImageIcon(imageFolder + "ProcessNewBarcode.png");
      ICB_PROCESS_NEW_BARCODE_HOVER = new ImageIcon(imageFolder + "ProcessNewBarcodeHover.png");
		ICB_PROCESSFEE_HOVER = new ImageIcon(imageFolder + "ProcessFeeHoverC.png");
		ICB_EXIT_HOVER = new ImageIcon(imageFolder + "ExitHoverC.png");
		ICB_EXPORT_HOVER = new ImageIcon(imageFolder + "ExportHover.png");
	}
	public static ImageIcon ICB_LOGIN;
	public static ImageIcon ICB_CANCEL;
	public static ImageIcon ICB_SUBMIT;
	public static ImageIcon ICB_BACK;
	public static ImageIcon ICB_DONE;
	public static ImageIcon ICB_SEARCH;
	public static ImageIcon ICB_SELECT;
	public static ImageIcon ICB_PRINT;
	public static ImageIcon ICB_PROCESSFEE;
	public static ImageIcon ICB_EXIT;
	public static ImageIcon ICB_LOGIN_HOVER;
	public static ImageIcon ICB_CANCEL_HOVER;
	public static ImageIcon ICB_SUBMIT_HOVER;
	public static ImageIcon ICB_BACK_HOVER;
	public static ImageIcon ICB_DONE_HOVER;
	public static ImageIcon ICB_SEARCH_HOVER;
	public static ImageIcon ICB_SELECT_HOVER;
	public static ImageIcon ICB_PRINT_HOVER;
   public static ImageIcon ICB_PROCESS_BARCODE;
   public static ImageIcon ICB_PROCESS_BARCODE_HOVER;
   public static ImageIcon ICB_PROCESS_NEW_BARCODE;
   public static ImageIcon ICB_PROCESS_NEW_BARCODE_HOVER;
	public static ImageIcon ICB_PROCESSFEE_HOVER;
	public static ImageIcon ICB_EXIT_HOVER;
	public static ImageIcon ICB_EXPORT;
	public static ImageIcon ICB_EXPORT_HOVER;
	public static ImageIcon ICB_VALIDATE;
	public static int NUM_MENU_IMGS;
	public static boolean IMG_DONE = false;
	public static Image JPI_BK_IMG_0 = null;
	public static Image BK_IMG_0 = null;
	public static Image LG_BK_IMG_0 = null;
	public static Image LG_BK_IMG_1 = null;
	public static ImageIcon[] ICS;
	public static ImageIcon[] ICSP;
	public static ImageIcon[] ICSH;
	public static ImageIcon ICS_LOGOUT;
	public static ImageIcon ICS_CHANGE_PASSWORD;
	public static ImageIcon ICS_LOGOUT_HOVER;
	public static ImageIcon ICS_CHANGE_PASSWORD_HOVER;
	public static ImageIcon IC_ADD_BOOK;
	public static ImageIcon IC_MODIFY_BOOK;
	public static ImageIcon IC_DELETE_BOOK;
	public static ImageIcon IC_ADD_BORROWER;
	public static ImageIcon IC_MODIFY_BORROWER;
	public static ImageIcon IC_DELETE_BORROWER;
	public static ImageIcon IC_ADD_WORKER;
	public static ImageIcon IC_MODIFY_WORKER;
	public static ImageIcon IC_DELETE_WORKER;
	public static ImageIcon IC_CHECK_IN_BOOK;
	public static ImageIcon IC_CHECK_OUT_BOOK;
	public static ImageIcon IC_PROCESS_LOST_BOOK;
	public static ImageIcon IC_AVAILABLE_BOOKS;
	public static ImageIcon IC_CHECKED_OUT_BOOKS;
	public static ImageIcon IC_SB_WITH_CO_BOOKS;
	public static ImageIcon IC_DELINQUNECY_CHECK;
	public static ImageIcon IC_ADD_BOOK_HOVER;
	public static ImageIcon IC_MODIFY_BOOK_HOVER;
	public static ImageIcon IC_DELETE_BOOK_HOVER;
	public static ImageIcon IC_ADD_BORROWER_HOVER;
	public static ImageIcon IC_MODIFY_BORROWER_HOVER;
	public static ImageIcon IC_DELETE_BORROWER_HOVER;
	public static ImageIcon IC_ADD_WORKER_HOVER;
	public static ImageIcon IC_MODIFY_WORKER_HOVER;
	public static ImageIcon IC_DELETE_WORKER_HOVER;
	public static ImageIcon IC_CHECK_IN_BOOK_HOVER;
	public static ImageIcon IC_CHECK_OUT_BOOK_HOVER;
	public static ImageIcon IC_PROCESS_LOST_BOOK_HOVER;
	public static ImageIcon IC_AVAILABLE_BOOKS_HOVER;
	public static ImageIcon IC_CHECKED_OUT_BOOKS_HOVER;
	public static ImageIcon IC_SB_WITH_CO_BOOKS_HOVER;
	public static ImageIcon IC_DELINQUNECY_CHECK_HOVER;
}
