#!/bin/bash
#
#Time of day greeting (Author: Jason Laske, Date: 04/16/2014)
#
if [[ $# -eq 0 ]]
   then
	hour=`date +%H`	# command output substitution
   else
	hour=$1
fi
#
#Check to see if the $hour is less than 0 or greater than 23
#
if [[ $hour -lt 0 || $hour -gt 23 ]]
   then 
	echo "usage: $0 (A integer value between 0 and 23)"
   	exit 1
fi
#
if [[ $hour -lt 12 ]]
   then
	echo "Good Morning!"
   else
	if [[ $hour -lt 18 ]]
	  then
		echo "Good Afternoon!"
	  else
		echo "Good Evening!"
	fi
fi
#
exit 0
#
